name: cangeosolution_adminplayer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  file_picker: ^8.3.1
  video_player: ^2.9.2
  chewie: ^1.10.0
  fl_chart: ^0.63.0
  intl: ^0.20.2
  dropdown_button2: ^2.3.9
  loading_animation_widget: ^1.3.0
  liquid_progress_indicator_v2: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
    - images/logo.png
    

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
